Add workaround to support k8s v1.29
ionos-cloud/cluster-api-provider-proxmox pull request #127
Opened 2024-02-28 15:53 UTC by mcbenjemaa

2024-02-29 15:35 UTC, mcbenjemaa commented
https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/113
will be handled in this PR

2024-02-29 19:55 UTC, lubedacht requested changes

2024-02-29 19:55 UTC, lubedacht commented on templates/cluster-template.yaml
> +              image: ghcr.io/kube-vip/kube-vip:v0.6.4
Latest version is [v0.7.1](https://github.com/kube-vip/kube-vip/releases/tag/v0.7.1)

2024-03-11 22:39 UTC, mcbenjemaa commented
Tested ✅

2024-03-12 14:07 UTC, merged