fix(mockery): add missing boilerplate for mocker
ionos-cloud/cluster-api-provider-proxmox pull request #234
Opened 2024-06-10 14:59 UTC by CiraciNicolo

This lightweight commits fix the mockgen phony by providing the needed file. 

I don't know if the omission is on a voluntary basis but I think this should not break the make process.

2024-06-10 15:39 UTC, mcbenjemaa approved these changes

2024-06-11 05:30 UTC, wikkyk requested changes
I consciously decided against this as it kept causing issues with the actual copyright headers.
What's breaking, exactly?

2024-06-11 06:01 UTC, CiraciNicolo commented
The mockgen phony, and therefore any make with new functions implemented or signature edits.

2024-06-11 07:57 UTC, wikkyk commented
Thanks for letting us know. I would prefer to remove the line from the mockery config instead: see #235.

2024-06-11 07:57 UTC, closed without merging