Adjust cloudinit to support dhcp
ionos-cloud/cluster-api-provider-proxmox pull request #44
Opened 2023-12-18 20:13 UTC by mcbenjemaa

2023-12-19 15:27 UTC, mcbenjemaa commented on pkg/cloudinit/network.go
> +      {{- if $element.DHCP4 }}
done, you can check

2023-12-19 15:28 UTC, mcbenjemaa commented
Tested ✅

2023-12-19 20:07 UTC, avorima requested changes

2023-12-19 20:07 UTC, avorima commented on pkg/cloudinit/network_test.go
Please remove the `InvalidNetworkConfigMalformedIp` test case. It is duplicated with `InvalidNetworkConfigMalformedIP`

2023-12-20 10:18 UTC, mcbenjemaa commented on pkg/cloudinit/network_test.go
right

2023-12-20 13:11 UTC, avorima approved these changes

2023-12-20 13:53 UTC, merged